# Generated by Django 4.1 on 2023-05-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_qunatity_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'orders'},
        ),
    ]
